SELECT SUBSTR(PHONE_NUMBER,1,3) AS Operator, COUNT(*) AS Total FROM HR.EMPLOYEES GROUP BY SUBSTR(PHONE_NUMBER,1,3) ORDER BY OPERATOR ASC;

SELECT * FROM(
SELECT SUBSTR(PHONE_NUMBER,1,3) AS Operator, COUNT(*) AS Total FROM HR.EMPLOYEES GROUP BY SUBSTR(PHONE_NUMBER,1,3))
PIVOT(
    SUM (Total)
    FOR Operator
    IN(515,590,603,'011',650)
);