CREATE TABLE HR.CUSTOMER(
CUSTOMERNAME VARCHAR(50)
);

INSERT INTO HR.CUSTOMER VALUES('NEÞET BEKTAÞ');
INSERT INTO HR.CUSTOMER VALUES('HASAN YARÝN');
INSERT INTO HR.CUSTOMER VALUES('HÜSEYÝN ÖZLEMÝÞ');
INSERT INTO HR.CUSTOMER VALUES('YILMAZ YÜCER');
INSERT INTO HR.CUSTOMER VALUES('MEHMET ÞERÝF KURT');
INSERT INTO HR.CUSTOMER VALUES('LEVENT HACIOÐLU');
INSERT INTO HR.CUSTOMER VALUES('HASAN YAMAN');
INSERT INTO HR.CUSTOMER VALUES('ÖZGÜR KANÞIRAY');
INSERT INTO HR.CUSTOMER VALUES('YAKUP HÜSEYÝN HIÇKIRAN');
INSERT INTO HR.CUSTOMER VALUES('HÜLYA BALTUTAN');
INSERT INTO HR.CUSTOMER VALUES('SÝAWASH  ABDULQAYOM');
INSERT INTO HR.CUSTOMER VALUES('NERÝMAN ÇÝÇEKÇÝ');

SELECT * FROM HR.customer;

  
SELECT LPAD (REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,1),2)
|| REGEXP_REPLACE((SUBSTR(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,1),3,LENGTH(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,1)))),'.','*')
|| ' '||
LPAD(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,2),2)
|| REGEXP_REPLACE((SUBSTR(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,2),3,LENGTH(REGEXP_SUBSTR(CUSTOMERNAME, '[^ ]+' ,1,2)))) ,'.','*')
|| ' ' ||
LPAD(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+',1,3),2)
||REGEXP_REPLACE((SUBSTR(REGEXP_SUBSTR(CUSTOMERNAME,'[^ ]+ ',1,3),3,LENGTH(REGEXP_SUBSTR(CUSTOMERNAME, '[^ ]+' ,1,3)))) ,'.','*') AS CUSTOMERNAME
FROM HR.customer;

