CREATE TABLE  HR.EMP AS (SELECT * FROM HR.employees);
SELECT * FROM HR.emp;

INSERT INTO HR.emp (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID) 
VALUES(207,'AHMET','TURHAN','AHMET@MAÝL','16','26/07/2021','INTERN',100,0,554,1);

UPDATE HR.emp SET phone_number = '5546465757' WHERE EMPLOYEE_ID = 207;

UPDATE HR.emp SET salary = '700' WHERE EMPLOYEE_ID = 207;

DELETE FROM HR.emp WHERE EMPLOYEE_ID = 207;

DROP TABLE HR.emp;